// This file is auto-generated by @hey-api/openapi-ts

export const AdminArticlePublicSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        source: {
            type: 'string',
            maxLength: 64,
            title: 'Source'
        },
        excerpt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Excerpt'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        author: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Author'
        },
        category: {
            type: 'string',
            enum: ['agents', 'rag', 'models', 'infrastructure', 'engineering', 'research', 'applications', 'business', 'policy', 'safety', 'other'],
            title: 'Category'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        },
        published_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        fetched_at: {
            type: 'string',
            format: 'date-time',
            title: 'Fetched At'
        },
        saved_count: {
            type: 'integer',
            title: 'Saved Count'
        }
    },
    type: 'object',
    required: ['url', 'title', 'source', 'category', 'id', 'fetched_at', 'saved_count'],
    title: 'AdminArticlePublic'
} as const;

export const AdminArticlesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AdminArticlePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AdminArticlesPublic'
} as const;

export const ArticlePublicSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        source: {
            type: 'string',
            maxLength: 64,
            title: 'Source'
        },
        excerpt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Excerpt'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        author: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Author'
        },
        category: {
            type: 'string',
            enum: ['agents', 'rag', 'models', 'infrastructure', 'engineering', 'research', 'applications', 'business', 'policy', 'safety', 'other'],
            title: 'Category'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        },
        published_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        fetched_at: {
            type: 'string',
            format: 'date-time',
            title: 'Fetched At'
        }
    },
    type: 'object',
    required: ['url', 'title', 'source', 'category', 'id', 'fetched_at'],
    title: 'ArticlePublic'
} as const;

export const ArticlesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ArticlePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ArticlesPublic'
} as const;

export const BackfillResponseSchema = {
    properties: {
        processed: {
            type: 'integer',
            title: 'Processed'
        },
        remaining: {
            type: 'integer',
            title: 'Remaining'
        },
        batches: {
            type: 'integer',
            title: 'Batches'
        }
    },
    type: 'object',
    required: ['processed', 'remaining', 'batches'],
    title: 'BackfillResponse',
    description: `Wire shape of the backfill report.

Mirrors \`\`services.embeddings.BackfillReport\`\` but as a Pydantic
BaseModel so FastAPI serializes it cleanly without a custom encoder.`
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const DigestArticlePublicSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        source: {
            type: 'string',
            maxLength: 64,
            title: 'Source'
        },
        excerpt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Excerpt'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        author: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Author'
        },
        category: {
            type: 'string',
            enum: ['agents', 'rag', 'models', 'infrastructure', 'engineering', 'research', 'applications', 'business', 'policy', 'safety', 'other'],
            title: 'Category'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        },
        published_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        fetched_at: {
            type: 'string',
            format: 'date-time',
            title: 'Fetched At'
        },
        reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        }
    },
    type: 'object',
    required: ['url', 'title', 'source', 'category', 'id', 'fetched_at'],
    title: 'DigestArticlePublic',
    description: `ArticlePublic plus the recommender's reason string.

Matches ForYouArticlePublic's shape so the frontend can reuse the
same article-card rendering and reason-badge component.`
} as const;

export const DigestPublicSchemaSchema = {
    properties: {
        generated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Generated At'
        },
        window_start: {
            type: 'string',
            format: 'date-time',
            title: 'Window Start'
        },
        is_personalized: {
            type: 'boolean',
            title: 'Is Personalized'
        },
        sections: {
            items: {
                '$ref': '#/components/schemas/DigestSectionPublic'
            },
            type: 'array',
            title: 'Sections'
        }
    },
    type: 'object',
    required: ['generated_at', 'window_start', 'is_personalized', 'sections'],
    title: 'DigestPublicSchema'
} as const;

export const DigestSectionPublicSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        articles: {
            items: {
                '$ref': '#/components/schemas/DigestArticlePublic'
            },
            type: 'array',
            title: 'Articles'
        }
    },
    type: 'object',
    required: ['key', 'title', 'articles'],
    title: 'DigestSectionPublic'
} as const;

export const FeedbackCreateSchema = {
    properties: {
        category: {
            type: 'string',
            enum: ['general', 'missing_topic_source_tag', 'bad_recommendation', 'feature_request', 'bug_report'],
            title: 'Category'
        },
        message: {
            type: 'string',
            maxLength: 2000,
            minLength: 10,
            title: 'Message'
        },
        context: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Context'
        }
    },
    type: 'object',
    required: ['category', 'message'],
    title: 'FeedbackCreate'
} as const;

export const FeedbackPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        category: {
            type: 'string',
            enum: ['general', 'missing_topic_source_tag', 'bad_recommendation', 'feature_request', 'bug_report'],
            title: 'Category'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        context: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Context'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'category', 'message', 'created_at', 'updated_at'],
    title: 'FeedbackPublic'
} as const;

export const ForYouArticleDebugPublicSchema = {
    properties: {
        breakdown: {
            '$ref': '#/components/schemas/ScoreBreakdownPublic'
        },
        was_exploration_injection: {
            type: 'boolean',
            title: 'Was Exploration Injection'
        }
    },
    type: 'object',
    required: ['breakdown', 'was_exploration_injection'],
    title: 'ForYouArticleDebugPublic',
    description: `Diagnostic payload attached to each For-You article when \`\`?debug=1\`\`.

Populated only when the request asks for debug AND the caller is a
superuser — non-superusers always see \`\`None\`\` here regardless of the
query param (see the route handler for the silent-ignore policy).`
} as const;

export const ForYouArticlePublicSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        source: {
            type: 'string',
            maxLength: 64,
            title: 'Source'
        },
        excerpt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Excerpt'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        author: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Author'
        },
        category: {
            type: 'string',
            enum: ['agents', 'rag', 'models', 'infrastructure', 'engineering', 'research', 'applications', 'business', 'policy', 'safety', 'other'],
            title: 'Category'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        },
        published_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        fetched_at: {
            type: 'string',
            format: 'date-time',
            title: 'Fetched At'
        },
        reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        },
        debug: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ForYouArticleDebugPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['url', 'title', 'source', 'category', 'id', 'fetched_at'],
    title: 'ForYouArticlePublic',
    description: `Article + recommendation reason label, plus optional debug payload.

The reason is built server-side from the dominant scoring component
(see \`\`services.recommender.reason_for\`\`). Optional because pure-recency
recommendations may not justify a badge.

\`\`debug\`\` is populated only when the caller is a superuser AND passed
\`\`?debug=1\`\`. Non-superusers always see \`\`None\`\` here, even if they
pass the query param — the route handler silently ignores the flag
rather than 403'ing, so a superuser's debug URL pasted to a regular
user just renders the normal feed.`
} as const;

export const ForYouArticlesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ForYouArticlePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        candidate_pool_cap: {
            type: 'integer',
            title: 'Candidate Pool Cap'
        },
        weights: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ScoringWeightsPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['data', 'count', 'candidate_pool_cap'],
    title: 'ForYouArticlesPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const IngestRunPublicSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        started_at: {
            type: 'string',
            title: 'Started At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        },
        status: {
            type: 'string',
            enum: ['running', 'succeeded', 'failed'],
            title: 'Status'
        },
        inserted: {
            type: 'integer',
            title: 'Inserted'
        },
        skipped: {
            type: 'integer',
            title: 'Skipped'
        },
        embedded: {
            type: 'integer',
            title: 'Embedded'
        },
        duration_ms: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Ms'
        },
        errors: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Errors'
        }
    },
    type: 'object',
    required: ['id', 'started_at', 'finished_at', 'status', 'inserted', 'skipped', 'embedded', 'duration_ms', 'errors'],
    title: 'IngestRunPublic',
    description: `Wire shape of one run.

Fields mirror the IngestRun model with two adjustments:
  - id is serialized as a string (UUID) for the JS client.
  - errors is always a list of strings; the model's JSONB column
    could hold richer structures in the future, but the current
    contract is "human-readable error messages."`
} as const;

export const IngestRunsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/IngestRunPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'IngestRunsPublic',
    description: `Paginated wrapper. \`\`count\`\` is the page size, not a total —
listing is bounded and the admin page doesn't paginate yet.`
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const OAuthAccountPublicSchema = {
    properties: {
        provider: {
            type: 'string',
            title: 'Provider'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        email_verified: {
            type: 'boolean',
            title: 'Email Verified'
        },
        display_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Name'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['provider', 'email', 'email_verified', 'created_at'],
    title: 'OAuthAccountPublic'
} as const;

export const OAuthAccountsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/OAuthAccountPublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'OAuthAccountsPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const SavedArticleIdsPublicSchema = {
    properties: {
        article_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Article Ids'
        }
    },
    type: 'object',
    required: ['article_ids'],
    title: 'SavedArticleIdsPublic'
} as const;

export const SavedArticlesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ArticlePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SavedArticlesPublic'
} as const;

export const ScoreBreakdownPublicSchema = {
    properties: {
        semantic: {
            type: 'number',
            title: 'Semantic'
        },
        explicit: {
            type: 'number',
            title: 'Explicit'
        },
        source: {
            type: 'number',
            title: 'Source'
        },
        recency: {
            type: 'number',
            title: 'Recency'
        },
        weighted_semantic: {
            type: 'number',
            title: 'Weighted Semantic'
        },
        weighted_explicit: {
            type: 'number',
            title: 'Weighted Explicit'
        },
        weighted_source: {
            type: 'number',
            title: 'Weighted Source'
        },
        weighted_recency: {
            type: 'number',
            title: 'Weighted Recency'
        },
        total: {
            type: 'number',
            title: 'Total'
        },
        dominant_signal: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dominant Signal'
        }
    },
    type: 'object',
    required: ['semantic', 'explicit', 'source', 'recency', 'weighted_semantic', 'weighted_explicit', 'weighted_source', 'weighted_recency', 'total', 'dominant_signal'],
    title: 'ScoreBreakdownPublic',
    description: `Per-article scoring components, surfaced for the admin debug panel.

Mirrors \`\`services.recommender.ScoreBreakdown\`\` but pre-computes the
weighted contributions (\`\`weighted_*\`\`) server-side. The frontend
wants weighted values to render the dominant signal — making the FE
recompute would mean duplicating \`\`ScoringWeights\`\` constants in JS
and risking drift when we tune. Sending both raw and weighted is
four extra floats and removes that whole class of bug.`
} as const;

export const ScoringWeightsPublicSchema = {
    properties: {
        semantic: {
            type: 'number',
            title: 'Semantic'
        },
        explicit: {
            type: 'number',
            title: 'Explicit'
        },
        source: {
            type: 'number',
            title: 'Source'
        },
        recency: {
            type: 'number',
            title: 'Recency'
        }
    },
    type: 'object',
    required: ['semantic', 'explicit', 'source', 'recency'],
    title: 'ScoringWeightsPublic',
    description: `The four weights used by the recommender, surfaced in the debug envelope.

Lets the debug panel header show "weights: 0.30 / 0.40 / 0.15 / 0.15"
so a weight tuning experiment is visible at a glance without reading
code. Only included when the request asks for debug.`
} as const;

export const SourcePublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        default_category: {
            type: 'string',
            enum: ['agents', 'rag', 'models', 'infrastructure', 'engineering', 'research', 'applications', 'business', 'policy', 'safety', 'other'],
            title: 'Default Category'
        },
        source_type: {
            type: 'string',
            enum: ['official', 'independent', 'community', 'research', 'media', 'newsletter', 'analysis', 'policy', 'education', 'papers', 'podcast'],
            title: 'Source Type'
        },
        topic: {
            type: 'string',
            title: 'Topic'
        },
        description: {
            type: 'string',
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name', 'default_category', 'source_type', 'topic', 'description'],
    title: 'SourcePublic'
} as const;

export const SourcesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SourcePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SourcesPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserInterestPublicSchema = {
    properties: {
        categories: {
            items: {
                type: 'string',
                enum: ['agents', 'rag', 'models', 'infrastructure', 'engineering', 'research', 'applications', 'business', 'policy', 'safety', 'other']
            },
            type: 'array',
            title: 'Categories',
            default: []
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags',
            default: []
        },
        preferred_sources: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Preferred Sources',
            default: []
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    title: 'UserInterestPublic',
    description: `Wire shape returned to the client.

A user with no interests row in the DB still gets a valid response
with empty lists — the frontend treats absence and emptiness as the
same thing.`
} as const;

export const UserInterestUpdateSchema = {
    properties: {
        categories: {
            items: {
                type: 'string',
                enum: ['agents', 'rag', 'models', 'infrastructure', 'engineering', 'research', 'applications', 'business', 'policy', 'safety', 'other']
            },
            type: 'array',
            maxItems: 11,
            title: 'Categories'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 20,
            title: 'Tags'
        },
        preferred_sources: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 88,
            title: 'Preferred Sources'
        }
    },
    type: 'object',
    title: 'UserInterestUpdate',
    description: `PUT body for /users/me/interests.

Validation:
  - categories must be drawn from the Category Literal (Pydantic enforces).
  - tags are length- and count-bounded; normalized in \`normalized_tags\`.
  - preferred_sources must each be a known source name (validator below).`
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        has_password: {
            type: 'boolean',
            title: 'Has Password',
            default: true
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;