// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ArticlesReadArticlesData, ArticlesReadArticlesResponse, ArticlesReadSourcesData, ArticlesReadSourcesResponse, ArticlesReadArticleData, ArticlesReadArticleResponse, ArticlesReadSavedArticlesData, ArticlesReadSavedArticlesResponse, ArticlesReadSavedArticleIdsData, ArticlesReadSavedArticleIdsResponse, ArticlesSaveArticleData, ArticlesSaveArticleResponse, ArticlesUnsaveArticleData, ArticlesUnsaveArticleResponse, ArticlesGoToArticleData, ArticlesGoToArticleResponse, ArticlesDismissArticleData, ArticlesDismissArticleResponse, IngestTriggerIngestData, IngestTriggerIngestResponse, InterestsReadInterestsData, InterestsReadInterestsResponse, InterestsUpdateInterestsData, InterestsUpdateInterestsResponse, ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginRefreshSessionData, LoginRefreshSessionResponse, LoginLogoutResponse, LoginTestTokenData, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersReadUserMeData, UsersReadUserMeResponse, UsersDeleteUserMeData, UsersDeleteUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class ArticlesService {
    /**
     * Read Articles
     * Retrieve articles.
     * @param data The data for the request.
     * @param data.category
     * @param data.search
     * @param data.source
     * @param data.skip
     * @param data.limit
     * @returns ArticlesPublic Successful Response
     * @throws ApiError
     */
    public static readArticles(data: ArticlesReadArticlesData = {}): CancelablePromise<ArticlesReadArticlesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/articles/',
            query: {
                category: data.category,
                search: data.search,
                source: data.source,
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Sources
     * Retrieve configured article sources.
     * @param data The data for the request.
     * @param data.sourceType
     * @returns SourcesPublic Successful Response
     * @throws ApiError
     */
    public static readSources(data: ArticlesReadSourcesData = {}): CancelablePromise<ArticlesReadSourcesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/articles/sources/',
            query: {
                source_type: data.sourceType
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Article
     * Get article by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ArticlePublic Successful Response
     * @throws ApiError
     */
    public static readArticle(data: ArticlesReadArticleData): CancelablePromise<ArticlesReadArticleResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/articles/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Saved Articles
     * Get current user's saved articles.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.accessToken
     * @returns SavedArticlesPublic Successful Response
     * @throws ApiError
     */
    public static readSavedArticles(data: ArticlesReadSavedArticlesData = {}): CancelablePromise<ArticlesReadSavedArticlesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/articles/saved/',
            cookies: {
                access_token: data.accessToken
            },
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Saved Article Ids
     * Get IDs of all articles saved by current user (for UI state).
     * @param data The data for the request.
     * @param data.accessToken
     * @returns SavedArticleIdsPublic Successful Response
     * @throws ApiError
     */
    public static readSavedArticleIds(data: ArticlesReadSavedArticleIdsData = {}): CancelablePromise<ArticlesReadSavedArticleIdsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/articles/saved/ids',
            cookies: {
                access_token: data.accessToken
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Save Article
     * Save an article for the current user.
     * @param data The data for the request.
     * @param data.articleId
     * @param data.accessToken
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static saveArticle(data: ArticlesSaveArticleData): CancelablePromise<ArticlesSaveArticleResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/articles/{article_id}/save',
            path: {
                article_id: data.articleId
            },
            cookies: {
                access_token: data.accessToken
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Unsave Article
     * Remove article from saved list.
     * @param data The data for the request.
     * @param data.articleId
     * @param data.accessToken
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static unsaveArticle(data: ArticlesUnsaveArticleData): CancelablePromise<ArticlesUnsaveArticleResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/articles/{article_id}/save',
            path: {
                article_id: data.articleId
            },
            cookies: {
                access_token: data.accessToken
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Go To Article
     * Log a click and 302-redirect to the article's external URL.
     *
     * Auth is optional: anonymous users get the redirect with no logging,
     * signed-in users get the click recorded as a behavioral signal for the
     * recommender. Logging is best-effort — navigation is the contract.
     *
     * The destination URL comes from the article row in the DB (never from a
     * query parameter), which means this endpoint cannot be repurposed as an
     * open redirect by an attacker. The scheme is whitelisted defensively.
     * @param data The data for the request.
     * @param data.articleId
     * @param data.accessToken
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static goToArticle(data: ArticlesGoToArticleData): CancelablePromise<ArticlesGoToArticleResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/articles/{article_id}/go',
            path: {
                article_id: data.articleId
            },
            cookies: {
                access_token: data.accessToken
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Dismiss Article
     * Mark an article as dismissed by the current user.
     *
     * Dismissed articles are hard-filtered out of the For-You feed (see
     * `recommender.filter_candidates`). Idempotent — a second dismiss just
     * bumps the count and last_at.
     * @param data The data for the request.
     * @param data.articleId
     * @param data.accessToken
     * @returns void Successful Response
     * @throws ApiError
     */
    public static dismissArticle(data: ArticlesDismissArticleData): CancelablePromise<ArticlesDismissArticleResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/articles/{article_id}/dismiss',
            path: {
                article_id: data.articleId
            },
            cookies: {
                access_token: data.accessToken
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class IngestService {
    /**
     * Trigger Ingest
     * @param data The data for the request.
     * @param data.accessToken
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static triggerIngest(data: IngestTriggerIngestData = {}): CancelablePromise<IngestTriggerIngestResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/ingest',
            cookies: {
                access_token: data.accessToken
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class InterestsService {
    /**
     * Read Interests
     * Current user's stored interests, or empty defaults if none set.
     * @param data The data for the request.
     * @param data.accessToken
     * @returns UserInterestPublic Successful Response
     * @throws ApiError
     */
    public static readInterests(data: InterestsReadInterestsData = {}): CancelablePromise<InterestsReadInterestsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me/interests',
            cookies: {
                access_token: data.accessToken
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Interests
     * Replace the current user's interests with the provided lists.
     *
     * Pydantic enforces that `body.categories` is a subset of the Category
     * Literal; tag normalization (lowercase, trim, dedupe, length cap) happens
     * in `body.normalized_tags()` before reaching the DB layer.
     * @param data The data for the request.
     * @param data.requestBody
     * @param data.accessToken
     * @returns UserInterestPublic Successful Response
     * @throws ApiError
     */
    public static updateInterests(data: InterestsUpdateInterestsData): CancelablePromise<InterestsUpdateInterestsResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/users/me/interests',
            cookies: {
                access_token: data.accessToken
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.accessToken
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            cookies: {
                access_token: data.accessToken
            },
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create new item.
     * @param data The data for the request.
     * @param data.requestBody
     * @param data.accessToken
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            cookies: {
                access_token: data.accessToken
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     * @param data The data for the request.
     * @param data.id
     * @param data.accessToken
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            cookies: {
                access_token: data.accessToken
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Update an item.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @param data.accessToken
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            cookies: {
                access_token: data.accessToken
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     * @param data The data for the request.
     * @param data.id
     * @param data.accessToken
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            cookies: {
                access_token: data.accessToken
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * Authenticate a user and start a cookie-backed session.
     *
     * Sets three cookies (access, refresh, is_logged_in marker) and also
     * returns the access token in the response body. The body is for the
     * test suite and isn't used by the frontend — production traffic
     * authenticates entirely via the cookies.
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Refresh Session
     * Mint a new access token using the refresh cookie.
     *
     * Rotates the refresh token too: each refresh issues a fresh refresh
     * cookie alongside the access cookie. This means a stolen refresh token
     * is single-use — the next legitimate refresh invalidates it (because
     * JWTs are stateless we can't actually invalidate the old one, but in
     * practice the legitimate user's next refresh will overwrite the cookie
     * and any subsequent attacker use will at least show stale activity).
     * Production-grade rotation requires server-side refresh-token tracking,
     * which we'd add via Redis if the project ever needed it.
     * @param data The data for the request.
     * @param data.refreshToken
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static refreshSession(data: LoginRefreshSessionData = {}): CancelablePromise<LoginRefreshSessionResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/refresh',
            cookies: {
                refresh_token: data.refreshToken
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Logout
     * Clear all auth cookies. No-op if the user wasn't logged in.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static logout(): CancelablePromise<LoginLogoutResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/logout'
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @param data The data for the request.
     * @param data.accessToken
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(data: LoginTestTokenData = {}): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token',
            cookies: {
                access_token: data.accessToken
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @param data.accessToken
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            cookies: {
                access_token: data.accessToken
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.accessToken
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            cookies: {
                access_token: data.accessToken
            },
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @param data.accessToken
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            cookies: {
                access_token: data.accessToken
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @param data.accessToken
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            cookies: {
                access_token: data.accessToken
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @param data The data for the request.
     * @param data.accessToken
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(data: UsersReadUserMeData = {}): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me',
            cookies: {
                access_token: data.accessToken
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @param data The data for the request.
     * @param data.accessToken
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(data: UsersDeleteUserMeData = {}): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me',
            cookies: {
                access_token: data.accessToken
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @param data.accessToken
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            cookies: {
                access_token: data.accessToken
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @param data.accessToken
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            cookies: {
                access_token: data.accessToken
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @param data.accessToken
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            cookies: {
                access_token: data.accessToken
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.accessToken
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            cookies: {
                access_token: data.accessToken
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @param data.accessToken
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            cookies: {
                access_token: data.accessToken
            },
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}