// This file is auto-generated by @hey-api/openapi-ts

export type ArticlePublic = {
    url: string;
    title: string;
    source: string;
    excerpt?: (string | null);
    image_url?: (string | null);
    author?: (string | null);
    category: 'agents' | 'rag' | 'models' | 'infrastructure' | 'engineering' | 'research' | 'applications' | 'business' | 'policy' | 'safety' | 'other';
    tags?: Array<(string)>;
    published_at?: (string | null);
    id: string;
    fetched_at: string;
};

export type category = 'agents' | 'rag' | 'models' | 'infrastructure' | 'engineering' | 'research' | 'applications' | 'business' | 'policy' | 'safety' | 'other';

export type ArticlesPublic = {
    data: Array<ArticlePublic>;
    count: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SavedArticleIdsPublic = {
    article_ids: Array<(string)>;
};

export type SavedArticlesPublic = {
    data: Array<ArticlePublic>;
    count: number;
};

export type SourcePublic = {
    name: string;
    default_category: 'agents' | 'rag' | 'models' | 'infrastructure' | 'engineering' | 'research' | 'applications' | 'business' | 'policy' | 'safety' | 'other';
    source_type: 'official' | 'independent' | 'community' | 'research' | 'media' | 'newsletter';
    topic: string;
    description: string;
};

export type default_category = 'agents' | 'rag' | 'models' | 'infrastructure' | 'engineering' | 'research' | 'applications' | 'business' | 'policy' | 'safety' | 'other';

export type source_type = 'official' | 'independent' | 'community' | 'research' | 'media' | 'newsletter';

export type SourcesPublic = {
    data: Array<SourcePublic>;
    count: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

/**
 * Wire shape returned to the client.
 *
 * A user with no interests row in the DB still gets a valid response
 * with empty lists — the frontend treats absence and emptiness as the
 * same thing.
 */
export type UserInterestPublic = {
    categories?: Array<('agents' | 'rag' | 'models' | 'infrastructure' | 'engineering' | 'research' | 'applications' | 'business' | 'policy' | 'safety' | 'other')>;
    tags?: Array<(string)>;
    updated_at?: (string | null);
};

/**
 * PUT body for /users/me/interests.
 *
 * Validation:
 * - categories must be drawn from the Category Literal (Pydantic enforces).
 * - tags are length- and count-bounded.
 */
export type UserInterestUpdate = {
    categories?: Array<('agents' | 'rag' | 'models' | 'infrastructure' | 'engineering' | 'research' | 'applications' | 'business' | 'policy' | 'safety' | 'other')>;
    tags?: Array<(string)>;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ArticlesReadArticlesData = {
    category?: ('agents' | 'rag' | 'models' | 'infrastructure' | 'engineering' | 'research' | 'applications' | 'business' | 'policy' | 'safety' | 'other' | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
    source?: (string | null);
};

export type ArticlesReadArticlesResponse = (ArticlesPublic);

export type ArticlesReadSourcesData = {
    sourceType?: ('official' | 'independent' | 'community' | 'research' | 'media' | 'newsletter' | null);
};

export type ArticlesReadSourcesResponse = (SourcesPublic);

export type ArticlesReadArticleData = {
    id: string;
};

export type ArticlesReadArticleResponse = (ArticlePublic);

export type ArticlesReadSavedArticlesData = {
    accessToken?: (string | null);
    limit?: number;
    skip?: number;
};

export type ArticlesReadSavedArticlesResponse = (SavedArticlesPublic);

export type ArticlesReadSavedArticleIdsData = {
    accessToken?: (string | null);
};

export type ArticlesReadSavedArticleIdsResponse = (SavedArticleIdsPublic);

export type ArticlesSaveArticleData = {
    accessToken?: (string | null);
    articleId: string;
};

export type ArticlesSaveArticleResponse = (unknown);

export type ArticlesUnsaveArticleData = {
    accessToken?: (string | null);
    articleId: string;
};

export type ArticlesUnsaveArticleResponse = (unknown);

export type ArticlesGoToArticleData = {
    accessToken?: (string | null);
    articleId: string;
};

export type ArticlesGoToArticleResponse = (unknown);

export type ArticlesDismissArticleData = {
    accessToken?: (string | null);
    articleId: string;
};

export type ArticlesDismissArticleResponse = (void);

export type IngestTriggerIngestData = {
    accessToken?: (string | null);
};

export type IngestTriggerIngestResponse = (unknown);

export type InterestsReadInterestsData = {
    accessToken?: (string | null);
};

export type InterestsReadInterestsResponse = (UserInterestPublic);

export type InterestsUpdateInterestsData = {
    accessToken?: (string | null);
    requestBody: UserInterestUpdate;
};

export type InterestsUpdateInterestsResponse = (UserInterestPublic);

export type ItemsReadItemsData = {
    accessToken?: (string | null);
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    accessToken?: (string | null);
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    accessToken?: (string | null);
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    accessToken?: (string | null);
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    accessToken?: (string | null);
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginRefreshSessionData = {
    refreshToken?: (string | null);
};

export type LoginRefreshSessionResponse = (Message);

export type LoginLogoutResponse = (Message);

export type LoginTestTokenData = {
    accessToken?: (string | null);
};

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    accessToken?: (string | null);
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    accessToken?: (string | null);
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    accessToken?: (string | null);
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersUpdateUserMeData = {
    accessToken?: (string | null);
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersReadUserMeData = {
    accessToken?: (string | null);
};

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeData = {
    accessToken?: (string | null);
};

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdatePasswordMeData = {
    accessToken?: (string | null);
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    accessToken?: (string | null);
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    accessToken?: (string | null);
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    accessToken?: (string | null);
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    accessToken?: (string | null);
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);
