// This file is auto-generated by @hey-api/openapi-ts

export type AdminArticlePublic = {
    url: string;
    title: string;
    source: string;
    excerpt?: (string | null);
    image_url?: (string | null);
    author?: (string | null);
    category: 'agents' | 'rag' | 'models' | 'infrastructure' | 'engineering' | 'research' | 'applications' | 'business' | 'policy' | 'safety' | 'education' | 'other';
    tags?: Array<(string)>;
    published_at?: (string | null);
    id: string;
    fetched_at: string;
    saved_count: number;
};

export type category = 'agents' | 'rag' | 'models' | 'infrastructure' | 'engineering' | 'research' | 'applications' | 'business' | 'policy' | 'safety' | 'education' | 'other';

export type AdminArticlesPublic = {
    data: Array<AdminArticlePublic>;
    count: number;
};

export type ArticleCleanupResponse = {
    archived_count: number;
    deleted_count: number;
    dry_run: boolean;
    archive_cutoff: (string | null);
    delete_cutoff: (string | null);
    keep_clicked_since: (string | null);
    errors: Array<(string)>;
};

export type ArticlePublic = {
    url: string;
    title: string;
    source: string;
    excerpt?: (string | null);
    image_url?: (string | null);
    author?: (string | null);
    category: 'agents' | 'rag' | 'models' | 'infrastructure' | 'engineering' | 'research' | 'applications' | 'business' | 'policy' | 'safety' | 'education' | 'other';
    tags?: Array<(string)>;
    published_at?: (string | null);
    id: string;
    fetched_at: string;
};

export type ArticlesPublic = {
    data: Array<ArticlePublic>;
    count: number;
};

/**
 * Wire shape of the backfill report.
 *
 * Mirrors ``services.embeddings.BackfillReport`` but as a Pydantic
 * BaseModel so FastAPI serializes it cleanly without a custom encoder.
 */
export type BackfillResponse = {
    processed: number;
    remaining: number;
    batches: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CtaLocationRow = {
    location: string;
    clicks: number;
    completed_signups?: (number | null);
    conversion_rate?: (number | null);
};

/**
 * ArticlePublic plus the recommender's reason string.
 *
 * Matches ForYouArticlePublic's shape so the frontend can reuse the
 * same article-card rendering and reason-badge component.
 */
export type DigestArticlePublic = {
    url: string;
    title: string;
    source: string;
    excerpt?: (string | null);
    image_url?: (string | null);
    author?: (string | null);
    category: 'agents' | 'rag' | 'models' | 'infrastructure' | 'engineering' | 'research' | 'applications' | 'business' | 'policy' | 'safety' | 'education' | 'other';
    tags?: Array<(string)>;
    published_at?: (string | null);
    id: string;
    fetched_at: string;
    reason?: (string | null);
};

/**
 * Body for the settings-page digest toggle.
 *
 * Allows changing the opt-in flag and the cached timezone independent
 * of the onboarding flow. Both fields are optional so the client can
 * update only what changed.
 */
export type DigestPreferencesUpdate = {
    daily_digest_enabled?: (boolean | null);
    timezone?: (string | null);
};

export type DigestPublicSchema = {
    generated_at: string;
    window_start: string;
    is_personalized: boolean;
    sections: Array<DigestSectionPublic>;
};

export type DigestSectionPublic = {
    key: string;
    title: string;
    articles: Array<DigestArticlePublic>;
};

export type FeedbackCreate = {
    category: 'general' | 'missing_topic_source_tag' | 'bad_recommendation' | 'feature_request' | 'bug_report';
    message: string;
    context?: ({
    [key: string]: unknown;
} | null);
};

export type category2 = 'general' | 'missing_topic_source_tag' | 'bad_recommendation' | 'feature_request' | 'bug_report';

export type FeedbackPublic = {
    id: string;
    user_id: string;
    category: 'general' | 'missing_topic_source_tag' | 'bad_recommendation' | 'feature_request' | 'bug_report';
    message: string;
    context?: ({
    [key: string]: unknown;
} | null);
    created_at: string;
    updated_at: string;
};

/**
 * Diagnostic payload attached to each For-You article when ``?debug=1``.
 *
 * Populated only when the request asks for debug AND the caller is a
 * superuser — non-superusers always see ``None`` here regardless of the
 * query param (see the route handler for the silent-ignore policy).
 */
export type ForYouArticleDebugPublic = {
    breakdown: ScoreBreakdownPublic;
    was_exploration_injection: boolean;
};

/**
 * Article + recommendation reason label, plus optional debug payload.
 *
 * The reason is built server-side from the dominant scoring component
 * (see ``services.recommender.reason_for``). Optional because pure-recency
 * recommendations may not justify a badge.
 *
 * ``debug`` is populated only when the caller is a superuser AND passed
 * ``?debug=1``. Non-superusers always see ``None`` here, even if they
 * pass the query param — the route handler silently ignores the flag
 * rather than 403'ing, so a superuser's debug URL pasted to a regular
 * user just renders the normal feed.
 */
export type ForYouArticlePublic = {
    url: string;
    title: string;
    source: string;
    excerpt?: (string | null);
    image_url?: (string | null);
    author?: (string | null);
    category: 'agents' | 'rag' | 'models' | 'infrastructure' | 'engineering' | 'research' | 'applications' | 'business' | 'policy' | 'safety' | 'education' | 'other';
    tags?: Array<(string)>;
    published_at?: (string | null);
    id: string;
    fetched_at: string;
    reason?: (string | null);
    debug?: (ForYouArticleDebugPublic | null);
};

export type ForYouArticlesPublic = {
    data: Array<ForYouArticlePublic>;
    count: number;
    candidate_pool_cap: number;
    weights?: (ScoringWeightsPublic | null);
};

/**
 * Raw event counts inside the selected window.
 */
export type FunnelCounts = {
    guest_page_view?: number;
    guest_article_click?: number;
    guest_source_click?: number;
    guest_topic_click?: number;
    guest_signup_click?: number;
    guest_login_click?: number;
    guest_signup_completed?: number;
};

/**
 * Derived conversion ratios. 0.0 when the denominator is zero.
 */
export type FunnelRates = {
    article_click_rate?: number;
    signup_click_rate?: number;
    signup_conversion_rate?: number;
};

/**
 * Payload for the public guest-event intake endpoint.
 *
 * Defined as a plain ``pydantic.BaseModel`` rather than ``SQLModel``
 * because SQLModel reserves the ``metadata`` attribute for SQLAlchemy's
 * ``MetaData`` binding; a field called ``metadata`` on a SQLModel
 * subclass is silently shadowed at instance-access time.
 */
export type GuestEventCreate = {
    anonymous_id: string;
    event_type: 'guest_page_view' | 'guest_article_click' | 'guest_source_click' | 'guest_topic_click' | 'guest_signup_click' | 'guest_login_click' | 'guest_signup_completed';
    path?: (string | null);
    article_id?: (string | null);
    /**
     * Logical source identifier. In AI Signal sources are keyed by their display name (see ``schemas.source.SOURCES``), so this accepts a string rather than a UUID.
     */
    source_id?: (string | null);
    topic?: (string | null);
    referrer?: (string | null);
    user_id?: (string | null);
    metadata?: ({
    [key: string]: unknown;
} | null);
};

export type event_type = 'guest_page_view' | 'guest_article_click' | 'guest_source_click' | 'guest_topic_click' | 'guest_signup_click' | 'guest_login_click' | 'guest_signup_completed';

export type GuestFunnelResponse = {
    range: '7d' | '30d' | '90d' | 'all';
    range_start?: (string | null);
    range_end: string;
    counts: FunnelCounts;
    rates: FunnelRates;
    top_articles: Array<TopArticleRow>;
    top_sources: Array<TopSourceRow>;
    top_topics: Array<TopTopicRow>;
    signup_cta_locations: Array<CtaLocationRow>;
};

export type range = '7d' | '30d' | '90d' | 'all';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Wire shape of one run.
 *
 * Fields mirror the IngestRun model with two adjustments:
 * - id is serialized as a string (UUID) for the JS client.
 * - errors is always a list of strings; the model's JSONB column
 * could hold richer structures in the future, but the current
 * contract is "human-readable error messages."
 */
export type IngestRunPublic = {
    id: string;
    started_at: string;
    finished_at: (string | null);
    status: 'running' | 'succeeded' | 'failed';
    inserted: number;
    skipped: number;
    embedded: number;
    duration_ms: (number | null);
    errors: Array<(string)>;
};

export type status = 'running' | 'succeeded' | 'failed';

/**
 * Paginated wrapper. ``count`` is the page size, not a total —
 * listing is bounded and the admin page doesn't paginate yet.
 */
export type IngestRunsPublic = {
    data: Array<IngestRunPublic>;
    count: number;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OAuthAccountPublic = {
    provider: string;
    email: string;
    email_verified: boolean;
    display_name?: (string | null);
    avatar_url?: (string | null);
    created_at: string;
};

export type OAuthAccountsPublic = {
    data: Array<OAuthAccountPublic>;
};

/**
 * Payload submitted at the end of the first-run onboarding flow.
 *
 * The client sends the timezone it detected from the browser plus
 * whether the user accepted the daily digest opt-in. The endpoint
 * sets ``onboarded_at = now()`` so the modal does not reopen.
 */
export type OnboardingComplete = {
    timezone?: (string | null);
    daily_digest_enabled?: boolean;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SavedArticleIdsPublic = {
    article_ids: Array<(string)>;
};

export type SavedArticlesPublic = {
    data: Array<ArticlePublic>;
    count: number;
};

/**
 * Per-article scoring components, surfaced for the admin debug panel.
 *
 * Mirrors ``services.recommender.ScoreBreakdown`` but pre-computes the
 * weighted contributions (``weighted_*``) server-side. The frontend
 * wants weighted values to render the dominant signal — making the FE
 * recompute would mean duplicating ``ScoringWeights`` constants in JS
 * and risking drift when we tune. Sending both raw and weighted is
 * four extra floats and removes that whole class of bug.
 */
export type ScoreBreakdownPublic = {
    semantic: number;
    explicit: number;
    source: number;
    recency: number;
    weighted_semantic: number;
    weighted_explicit: number;
    weighted_source: number;
    weighted_recency: number;
    total: number;
    dominant_signal: (string | null);
};

/**
 * The four weights used by the recommender, surfaced in the debug envelope.
 *
 * Lets the debug panel header show "weights: 0.30 / 0.40 / 0.15 / 0.15"
 * so a weight tuning experiment is visible at a glance without reading
 * code. Only included when the request asks for debug.
 */
export type ScoringWeightsPublic = {
    semantic: number;
    explicit: number;
    source: number;
    recency: number;
};

export type SourcePublic = {
    name: string;
    default_category: 'agents' | 'rag' | 'models' | 'infrastructure' | 'engineering' | 'research' | 'applications' | 'business' | 'policy' | 'safety' | 'education' | 'other';
    source_type: 'official' | 'independent' | 'community' | 'research' | 'media' | 'newsletter' | 'analysis' | 'policy' | 'education' | 'papers' | 'podcast' | 'video';
    topic: string;
    description: string;
};

export type default_category = 'agents' | 'rag' | 'models' | 'infrastructure' | 'engineering' | 'research' | 'applications' | 'business' | 'policy' | 'safety' | 'education' | 'other';

export type source_type = 'official' | 'independent' | 'community' | 'research' | 'media' | 'newsletter' | 'analysis' | 'policy' | 'education' | 'papers' | 'podcast' | 'video';

export type SourcesPublic = {
    data: Array<SourcePublic>;
    count: number;
};

export type SubscriptionCreate = {
    email: string;
};

export type SubscriptionPublic = {
    id: string;
    email: string;
    is_active: boolean;
    created_at: string;
    updated_at: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TopArticleRow = {
    article_id: string;
    title?: (string | null);
    source_name?: (string | null);
    url?: (string | null);
    published_at?: (string | null);
    guest_clicks: number;
};

export type TopSourceRow = {
    source_name: string;
    guest_clicks: number;
};

export type TopTopicRow = {
    topic: string;
    guest_clicks: number;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

/**
 * Wire shape returned to the client.
 *
 * A user with no interests row in the DB still gets a valid response
 * with empty lists — the frontend treats absence and emptiness as the
 * same thing.
 */
export type UserInterestPublic = {
    categories?: Array<('agents' | 'rag' | 'models' | 'infrastructure' | 'engineering' | 'research' | 'applications' | 'business' | 'policy' | 'safety' | 'education' | 'other')>;
    tags?: Array<(string)>;
    preferred_sources?: Array<(string)>;
    updated_at?: (string | null);
};

/**
 * PUT body for /users/me/interests.
 *
 * Validation:
 * - categories must be drawn from the Category Literal (Pydantic enforces).
 * - tags are length- and count-bounded; normalized in `normalized_tags`.
 * - preferred_sources must each be a known source name (validator below).
 */
export type UserInterestUpdate = {
    categories?: Array<('agents' | 'rag' | 'models' | 'infrastructure' | 'engineering' | 'research' | 'applications' | 'business' | 'policy' | 'safety' | 'education' | 'other')>;
    tags?: Array<(string)>;
    preferred_sources?: Array<(string)>;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    has_password?: boolean;
    created_at?: (string | null);
    timezone?: (string | null);
    daily_digest_enabled?: boolean;
    onboarded_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AdminReadAdminArticlesData = {
    accessToken?: (string | null);
    /**
     * Show only archived rows. Overrides include_archived.
     */
    archivedOnly?: boolean;
    /**
     * Include rows the cleanup pipeline has soft-archived. Default True so admins can inspect what's been hidden from end users.
     */
    includeArchived?: boolean;
    limit?: number;
    search?: (string | null);
    skip?: number;
    source?: (string | null);
};

export type AdminReadAdminArticlesResponse = (AdminArticlesPublic);

export type AdminDeleteAdminArticleData = {
    accessToken?: (string | null);
    articleId: string;
};

export type AdminDeleteAdminArticleResponse = (Message);

export type AdminEmbedPendingArticlesData = {
    accessToken?: (string | null);
    batchSize?: number;
    maxBatches?: number;
};

export type AdminEmbedPendingArticlesResponse = (BackfillResponse);

export type AdminPreviewDigestHtmlData = {
    accessToken?: (string | null);
    limit?: number;
    sample?: boolean;
    userId?: (string | null);
};

export type AdminPreviewDigestHtmlResponse = (string);

export type AdminReadIngestRunsData = {
    accessToken?: (string | null);
    limit?: number;
    status?: ('running' | 'succeeded' | 'failed' | null);
};

export type AdminReadIngestRunsResponse = (IngestRunsPublic);

export type AdminReadGuestFunnelData = {
    accessToken?: (string | null);
    range?: '7d' | '30d' | '90d' | 'all';
    topLimit?: number;
};

export type AdminReadGuestFunnelResponse = (GuestFunnelResponse);

export type AnalyticsRecordGuestEventData = {
    requestBody: GuestEventCreate;
};

export type AnalyticsRecordGuestEventResponse = (Message);

export type ArticlesReadArticlesData = {
    category?: ('agents' | 'rag' | 'models' | 'infrastructure' | 'engineering' | 'research' | 'applications' | 'business' | 'policy' | 'safety' | 'education' | 'other' | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
    source?: (string | null);
};

export type ArticlesReadArticlesResponse = (ArticlesPublic);

export type ArticlesReadForYouData = {
    accessToken?: (string | null);
    /**
     * Admin diagnostic: include per-article scoring breakdown and exploration-injection flags. Silently ignored for non-superusers.
     */
    debug?: boolean;
    limit?: number;
    skip?: number;
};

export type ArticlesReadForYouResponse = (ForYouArticlesPublic);

export type ArticlesReadFollowingData = {
    accessToken?: (string | null);
    limit?: number;
    skip?: number;
};

export type ArticlesReadFollowingResponse = (ArticlesPublic);

export type ArticlesReadSourcesData = {
    sourceType?: ('official' | 'independent' | 'community' | 'research' | 'media' | 'newsletter' | 'analysis' | 'policy' | 'education' | 'papers' | 'podcast' | 'video' | null);
};

export type ArticlesReadSourcesResponse = (SourcesPublic);

export type ArticlesReadSavedArticlesData = {
    accessToken?: (string | null);
    limit?: number;
    skip?: number;
};

export type ArticlesReadSavedArticlesResponse = (SavedArticlesPublic);

export type ArticlesReadSavedArticleIdsData = {
    accessToken?: (string | null);
};

export type ArticlesReadSavedArticleIdsResponse = (SavedArticleIdsPublic);

export type ArticlesReadArticleData = {
    id: string;
};

export type ArticlesReadArticleResponse = (ArticlePublic);

export type ArticlesSaveArticleData = {
    accessToken?: (string | null);
    articleId: string;
};

export type ArticlesSaveArticleResponse = (unknown);

export type ArticlesUnsaveArticleData = {
    accessToken?: (string | null);
    articleId: string;
};

export type ArticlesUnsaveArticleResponse = (unknown);

export type ArticlesGoToArticleData = {
    accessToken?: (string | null);
    articleId: string;
};

export type ArticlesGoToArticleResponse = (unknown);

export type ArticlesDismissArticleData = {
    accessToken?: (string | null);
    articleId: string;
};

export type ArticlesDismissArticleResponse = (void);

export type DigestReadTodayDigestData = {
    accessToken?: (string | null);
};

export type DigestReadTodayDigestResponse = (DigestPublicSchema);

export type FeedbackSubmitFeedbackData = {
    accessToken?: (string | null);
    requestBody: FeedbackCreate;
};

export type FeedbackSubmitFeedbackResponse = (FeedbackPublic);

export type IngestTriggerIngestData = {
    accessToken?: (string | null);
};

export type IngestTriggerIngestResponse = (unknown);

export type InterestsReadInterestsData = {
    accessToken?: (string | null);
};

export type InterestsReadInterestsResponse = (UserInterestPublic);

export type InterestsUpdateInterestsData = {
    accessToken?: (string | null);
    requestBody: UserInterestUpdate;
};

export type InterestsUpdateInterestsResponse = (UserInterestPublic);

export type InternalTriggerArticleCleanupData = {
    authorization?: (string | null);
    /**
     * Override request-level dry_run. Can force dry-run on a live deploy, but cannot downgrade an environment-level ARTICLE_CLEANUP_DRY_RUN=True default.
     */
    dryRun?: (boolean | null);
};

export type InternalTriggerArticleCleanupResponse = (ArticleCleanupResponse);

export type LoginStartOauthLoginData = {
    provider: string;
};

export type LoginStartOauthLoginResponse = (unknown);

export type LoginOauthCallbackData = {
    code?: (string | null);
    error?: (string | null);
    oauthState?: (string | null);
    provider: string;
    state?: (string | null);
};

export type LoginOauthCallbackResponse = (unknown);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginRefreshSessionData = {
    refreshToken?: (string | null);
};

export type LoginRefreshSessionResponse = (Message);

export type LoginLogoutData = {
    refreshToken?: (string | null);
};

export type LoginLogoutResponse = (Message);

export type LoginTestTokenData = {
    accessToken?: (string | null);
};

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    accessToken?: (string | null);
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SubscriptionsCreateSubscriptionData = {
    requestBody: SubscriptionCreate;
};

export type SubscriptionsCreateSubscriptionResponse = (SubscriptionPublic);

export type UsersReadUsersData = {
    accessToken?: (string | null);
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    accessToken?: (string | null);
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersUpdateUserMeData = {
    accessToken?: (string | null);
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersReadUserMeData = {
    accessToken?: (string | null);
};

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeData = {
    accessToken?: (string | null);
};

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdatePasswordMeData = {
    accessToken?: (string | null);
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersCompleteOnboardingData = {
    accessToken?: (string | null);
    requestBody: OnboardingComplete;
};

export type UsersCompleteOnboardingResponse = (UserPublic);

export type UsersUpdateDigestPreferencesData = {
    accessToken?: (string | null);
    requestBody: DigestPreferencesUpdate;
};

export type UsersUpdateDigestPreferencesResponse = (UserPublic);

export type UsersReadUserOauthAccountsData = {
    accessToken?: (string | null);
};

export type UsersReadUserOauthAccountsResponse = (OAuthAccountsPublic);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    accessToken?: (string | null);
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    accessToken?: (string | null);
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    accessToken?: (string | null);
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    accessToken?: (string | null);
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);