from app.crud.article import (
    count_articles,
    count_pending_embeddings,
    count_saved_articles,
    create_article,
    delete_article,
    get_article,
    get_article_by_url,
    get_articles,
    get_articles_by_ids,
    get_pending_embedding_articles,
    get_recent_articles_excluding,
    get_saved_article,
    get_saved_article_embeddings,
    get_saved_article_ids,
    get_saved_articles,
    get_saved_signals,
    save_article,
    unsave_article,
    update_article,
    update_article_embeddings,
)
from app.crud.event import (
    get_clicked_article_embeddings,
    get_clicked_signals,
    get_event_article_ids,
    get_events,
    record_event,
)
from app.crud.ingest_run import (
    fail_ingest_run,
    finish_ingest_run,
    list_ingest_runs,
    start_ingest_run,
)
from app.crud.interest import (
    get_interests,
    set_interests,
)
from app.crud.oauth_account import (
    create_oauth_account,
    get_oauth_account,
    update_oauth_account_profile,
)
from app.crud.refresh_session import (
    create_refresh_session,
    get_refresh_session_for_update,
    hash_refresh_token_id,
    refresh_session_is_active,
    revoke_refresh_sessions_for_user,
)
from app.crud.user import authenticate, create_user, get_user_by_email, update_user
from app.crud.user_embedding import (
    delete_user_embedding,
    get_user_embedding,
    upsert_user_embedding,
)

__all__ = [
    "authenticate",
    "count_articles",
    "count_pending_embeddings",
    "count_saved_articles",
    "create_article",
    "create_oauth_account",
    "create_user",
    "delete_article",
    "delete_user_embedding",
    "get_article",
    "get_article_by_url",
    "get_articles",
    "get_articles_by_ids",
    "get_clicked_article_embeddings",
    "get_clicked_signals",
    "get_event_article_ids",
    "get_events",
    "get_interests",
    "get_pending_embedding_articles",
    "get_recent_articles_excluding",
    "get_saved_article",
    "get_saved_article_embeddings",
    "get_saved_article_ids",
    "get_saved_articles",
    "get_saved_signals",
    "get_oauth_account",
    "get_user_by_email",
    "get_user_embedding",
    "record_event",
    "save_article",
    "set_interests",
    "unsave_article",
    "update_article",
    "update_article_embeddings",
    "update_oauth_account_profile",
    "update_user",
    "upsert_user_embedding",
    "create_refresh_session",
    "hash_refresh_token_id",
    "refresh_session_is_active",
    "revoke_refresh_sessions_for_user",
    "get_refresh_session_for_update",
    "fail_ingest_run",
    "finish_ingest_run",
    "list_ingest_runs",
    "start_ingest_run",
]
