from typing import Literal

from pydantic.dataclasses import dataclass
from sqlmodel import SQLModel

Category = Literal[
    "agents",
    "rag",
    "models",
    "infrastructure",
    "engineering",
    "research",
    "applications",
    "business",
    "policy",
    "safety",
    "education",
    "other",
]
SourceType = Literal[
    "official",
    "independent",
    "community",
    "research",
    "media",
    "newsletter",
    "analysis",
    "policy",
    "education",
    "papers",
    "podcast",
    "video",
]

CATEGORIES: tuple[Category, ...] = (
    "agents",
    "rag",
    "models",
    "infrastructure",
    "engineering",
    "research",
    "applications",
    "business",
    "policy",
    "safety",
    "education",
    "other",
)
SOURCE_TYPES: tuple[SourceType, ...] = (
    "official",
    "independent",
    "community",
    "research",
    "media",
    "newsletter",
    "analysis",
    "policy",
    "education",
    "papers",
    "podcast",
    "video",
)


@dataclass(frozen=True)
class Source:
    name: str
    rss_url: str
    default_category: Category
    source_type: SourceType = "independent"
    topic: str = "AI source"
    description: str = "Curated source for AI Signal."


class SourcePublic(SQLModel):
    name: str
    default_category: Category
    source_type: SourceType
    topic: str
    description: str


class SourcesPublic(SQLModel):
    data: list[SourcePublic]
    count: int


SOURCES: tuple[Source, ...] = (
    Source(
        "Anthropic",
        "https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_anthropic_engineering.xml",
        "models",
        "official",
        topic="AI Research Lab",
        description="Engineering updates from Anthropic on Claude, agents, evaluations, and reliable AI systems.",
    ),
    Source(
        "OpenAI",
        "https://openai.com/blog/rss.xml",
        "models",
        "official",
        topic="AI Research Lab",
        description="Official research, product, safety, and engineering updates from OpenAI.",
    ),
    Source(
        "Mistral AI",
        "https://raw.githubusercontent.com/0xSMW/rss-feeds/main/feeds/feed_mistral_news.xml",
        "models",
        "official",
        topic="European AI Lab",
        description="Official Mistral AI news on frontier models, open models, products, and deployment.",
    ),
    Source(
        "Google DeepMind",
        "https://deepmind.google/blog/rss.xml",
        "research",
        "official",
        topic="AI Research Lab",
        description="Research breakthroughs, product updates, and lab news from Google DeepMind.",
    ),
    Source(
        "Hugging Face Blog",
        "https://huggingface.co/blog/feed.xml",
        "engineering",
        "official",
        topic="Open AI Platform",
        description="Platform, model, dataset, and open source updates from the Hugging Face team.",
    ),
    Source(
        "Mozilla AI",
        "https://blog.mozilla.ai/rss/",
        "applications",
        "official",
        topic="Open Source AI Lab",
        description="Mozilla AI updates on open source AI, trustworthy products, builders, and community projects.",
    ),
    Source(
        "Google Research",
        "https://research.google/blog/rss/",
        "research",
        "official",
        topic="Corporate Research Lab",
        description="Latest research publications, methods, and project updates from Google Research.",
    ),
    Source(
        "Google AI Blog",
        "https://blog.google/technology/ai/rss/",
        "applications",
        "official",
        topic="AI Product and Research Updates",
        description="Official Google posts on Gemini, AI products, research launches, and applied AI features.",
    ),
    Source(
        "Perplexity Hub",
        "https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_perplexity_hub.xml",
        "applications",
        "official",
        topic="AI Search Product Updates",
        description="Perplexity product updates, research notes, and practical examples for AI search, agents, and knowledge work.",
    ),
    Source(
        "Meta Research",
        "https://research.facebook.com/feed/",
        "research",
        "official",
        topic="Corporate Research Lab",
        description="Research updates from Meta on machine learning, AI infrastructure, systems, and open research.",
    ),
    Source(
        "Microsoft Research AI",
        "https://www.microsoft.com/en-us/research/feed/?facet%5Btax%5D%5Bmsr-research-area%5D%5B0%5D=13556",
        "research",
        "official",
        topic="Corporate Research Lab",
        description="Microsoft Research posts on AI, machine learning, systems, agents, and responsible AI.",
    ),
    Source(
        "BAIR",
        "https://bair.berkeley.edu/blog/feed.xml",
        "research",
        "research",
        topic="Academic AI Lab",
        description="Research posts from the Berkeley Artificial Intelligence Research lab.",
    ),
    Source(
        "Stanford CRFM",
        "https://crfm.stanford.edu/feed.xml",
        "research",
        "research",
        topic="Foundation Model Research Lab",
        description="Research and policy work from Stanford's Center for Research on Foundation Models.",
    ),
    Source(
        "AI2 Blog",
        "https://allenai.org/rss.xml",
        "research",
        "research",
        topic="AI Research Institute",
        description="Research and engineering updates from the Allen Institute for AI on open models, science, NLP, and AI applications.",
    ),
    Source(
        "Mila Blog",
        "https://mila.quebec/en/research/blog/feed/",
        "research",
        "research",
        topic="Academic AI Lab",
        description="Research posts from Mila on machine learning, responsible AI, language models, and applied AI science.",
    ),
    Source(
        "Vector Institute",
        "https://vectorinstitute.ai/feed/",
        "research",
        "research",
        topic="AI Research Institute",
        description="Research, institute news, and applied AI updates from Canada's Vector Institute.",
    ),
    Source(
        "Epoch AI",
        "https://epochai.substack.com/feed",
        "research",
        "research",
        topic="AI Research Institute",
        description="Epoch AI research, forecasts, data insights, and Gradient Updates on AI progress.",
    ),
    Source(
        "Apple ML Research",
        "https://machinelearning.apple.com/rss.xml",
        "research",
        "official",
        topic="Corporate AI Research",
        description="Machine learning research papers, talks, and project updates from Apple.",
    ),
    Source(
        "Microsoft AI",
        "https://blogs.microsoft.com/blog/tag/ai/feed/",
        "models",
        "official",
        topic="AI Company Updates",
        description="Official Microsoft AI news covering Copilot, Azure AI, customers, and responsible AI.",
    ),
    Source(
        "AWS Machine Learning",
        "https://aws.amazon.com/blogs/machine-learning/feed/",
        "infrastructure",
        "official",
        topic="Cloud AI Platform",
        description="AWS posts on machine learning services, generative AI infrastructure, and production patterns.",
    ),
    Source(
        "NVIDIA GenAI",
        "https://developer.nvidia.com/blog/category/generative-ai/feed/",
        "infrastructure",
        "official",
        topic="AI Infrastructure",
        description="NVIDIA technical posts on generative AI, accelerated computing, and deployment tooling.",
    ),
    Source(
        "TensorFlow Blog",
        "https://blog.tensorflow.org/feeds/posts/default?alt=rss",
        "infrastructure",
        "official",
        topic="ML Framework",
        description="Official TensorFlow updates on model development, tooling, deployment, and machine learning research.",
    ),
    Source(
        "Cloudflare AI",
        "https://blog.cloudflare.com/tag/ai/rss/",
        "infrastructure",
        "official",
        topic="Edge AI Infrastructure",
        description="Cloudflare posts on AI inference, security, developer platforms, and production infrastructure.",
    ),
    Source(
        "OpenRouter",
        "https://openrouter.ai/announcements/feed.xml",
        "infrastructure",
        "official",
        topic="AI Model Routing Platform",
        description="OpenRouter announcements on model availability, routing, pricing, agents, and developer platform updates.",
    ),
    Source(
        "Ollama Blog",
        "https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_ollama.xml",
        "infrastructure",
        "official",
        topic="Local AI Runtime",
        description="Ollama updates on local model releases, tooling, integrations, and running open models on personal hardware.",
    ),
    Source(
        "LangChain",
        "https://www.langchain.com/blog/rss.xml",
        "agents",
        "official",
        topic="Agent Framework",
        description="Official LangChain updates on agents, LangGraph, retrieval, evaluations, and app development.",
    ),
    Source(
        "Aider",
        "https://aider.chat/feed.xml",
        "agents",
        "independent",
        topic="AI Coding Agent",
        description="Aider release notes, benchmarks, and practical findings on coding agents and LLM-assisted software development.",
    ),
    Source(
        "Cursor Blog",
        "https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_cursor.xml",
        "agents",
        "official",
        topic="AI Coding Environment",
        description="Cursor product and engineering updates on coding agents, developer workflows, models, and IDE features.",
    ),
    Source(
        "Windsurf Blog",
        "https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_windsurf_blog.xml",
        "agents",
        "official",
        topic="AI Coding Environment",
        description="Windsurf updates on AI coding agents, IDE capabilities, model integrations, and developer productivity workflows.",
    ),
    Source(
        "Weaviate",
        "https://weaviate.io/blog/rss.xml",
        "rag",
        "official",
        topic="Vector Database",
        description="Weaviate posts on vector search, RAG architecture, embeddings, and production AI retrieval.",
    ),
    Source(
        "LanceDB",
        "https://lancedb.com/blog/rss.xml",
        "rag",
        "official",
        topic="Vector Database",
        description="Technical posts on multimodal retrieval, vector search, embeddings, and AI data infrastructure.",
    ),
    Source(
        "Pinecone",
        "https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_pinecone.xml",
        "rag",
        "official",
        topic="Vector Database",
        description="Pinecone posts on vector search, RAG, retrieval infrastructure, embeddings, and production AI applications.",
    ),
    Source(
        "Modal",
        "https://modal.com/blog/atom.xml",
        "infrastructure",
        "official",
        topic="AI Cloud Infrastructure",
        description="Engineering posts on serverless compute, model serving, GPUs, and production AI workloads.",
    ),
    Source(
        "Modular",
        "https://www.modular.com/blog/rss.xml",
        "infrastructure",
        "official",
        topic="AI Runtime Infrastructure",
        description="Updates on Mojo, MAX, AI compilers, inference performance, and portable model deployment.",
    ),
    Source(
        "Together AI",
        "https://www.together.ai/blog/rss.xml",
        "models",
        "official",
        topic="AI Cloud Platform",
        description="Technical and product posts on open models, inference, fine-tuning, evaluations, and AI infrastructure.",
    ),
    Source(
        "Cohere",
        "https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_cohere.xml",
        "models",
        "official",
        topic="Enterprise AI Lab",
        description="Cohere updates on enterprise language models, retrieval, agents, multilingual AI, and deployment patterns.",
    ),
    Source(
        "Groq",
        "https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_groq.xml",
        "infrastructure",
        "official",
        topic="AI Inference Platform",
        description="Groq posts on fast inference, LPU infrastructure, model serving, developer examples, and AI application launches.",
    ),
    Source(
        "xAI News",
        "https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_xainews.xml",
        "models",
        "official",
        topic="Frontier AI Lab",
        description="xAI news on Grok model releases, product integrations, platform capabilities, and frontier model updates.",
    ),
    Source(
        "MLCommons",
        "https://mlcommons.org/feed/",
        "infrastructure",
        "independent",
        topic="AI Benchmarks",
        description="Benchmark, dataset, and standards updates for machine learning systems and AI performance.",
    ),
    Source(
        "Latent Space",
        "https://www.latent.space/feed",
        "engineering",
        "newsletter",
        topic="AI Engineering Newsletter",
        description="Technical AI engineering commentary and interviews with builders from leading AI teams.",
    ),
    Source(
        "AI News by Smol",
        "https://news.smol.ai/rss.xml",
        "engineering",
        "newsletter",
        topic="AI Builder News",
        description="Daily AI builder roundup tracking model releases, research, open source projects, and high-signal community discussion.",
    ),
    Source(
        "Ben's Bites",
        "https://www.bensbites.com/feed",
        "other",
        "newsletter",
        topic="AI Builder Newsletter",
        description="Popular daily AI newsletter covering model launches, tools, workflows, startups, and high-signal AI links.",
    ),
    Source(
        "The Neuron",
        "https://rss.beehiiv.com/feeds/N4eCstxvgX.xml",
        "other",
        "newsletter",
        topic="AI News Newsletter",
        description="Fast-moving AI newsletter covering social-platform trends, product launches, business shifts, and practical tools.",
    ),
    Source(
        "TLDR AI",
        "https://tldr.tech/api/rss/ai",
        "other",
        "newsletter",
        topic="AI News Briefing",
        description="Concise daily AI briefing covering research, products, tools, funding, and industry shifts.",
    ),
    Source(
        "The Sequence",
        "https://thesequence.substack.com/feed",
        "models",
        "newsletter",
        topic="AI Research and Industry Newsletter",
        description="Technical AI newsletter covering model research, ML infrastructure, AI products, and industry analysis.",
    ),
    Source(
        "Last Week in AI",
        "https://lastweekin.ai/feed",
        "other",
        "newsletter",
        topic="AI News Roundup",
        description="Weekly roundup of AI research, product launches, policy news, and industry developments.",
    ),
    Source(
        "Interconnects",
        "https://www.interconnects.ai/feed",
        "models",
        "analysis",
        topic="Model Research Analysis",
        description="Nathan Lambert's analysis of frontier models, open source AI, training, and policy.",
    ),
    Source(
        "One Useful Thing",
        "https://www.oneusefulthing.org/feed",
        "applications",
        "newsletter",
        topic="Applied AI Commentary",
        description="Ethan Mollick's writing on how AI affects work, education, organizations, and daily life.",
    ),
    Source(
        "No Priors",
        "https://feeds.megaphone.fm/nopriors",
        "business",
        "podcast",
        topic="AI Founder and Research Interviews",
        description="Sarah Guo and Elad Gil interview AI researchers, founders, and operators on frontier models, startups, and markets.",
    ),
    Source(
        "Eye On A.I.",
        "https://rss.libsyn.com/shows/123267/destinations/727317.xml",
        "business",
        "podcast",
        topic="AI Industry Interviews",
        description="Craig S. Smith interviews researchers, founders, and executives about AI breakthroughs, products, and global impact.",
    ),
    Source(
        "The TWIML AI Podcast",
        "https://feeds.megaphone.fm/MLN2155636147",
        "research",
        "podcast",
        topic="ML Research and Engineering Interviews",
        description="Sam Charrington interviews machine learning researchers and practitioners on applied AI, infrastructure, and emerging techniques.",
    ),
    Source(
        "Practical AI",
        "https://feeds.transistor.fm/practical-ai-machine-learning-data-science-llm",
        "engineering",
        "podcast",
        topic="Applied AI Engineering",
        description="Practical conversations on machine learning, data science, LLMs, MLOps, and real-world AI implementation.",
    ),
    Source(
        "The Cognitive Revolution",
        "https://feeds.megaphone.fm/RINTP3108857801",
        "models",
        "podcast",
        topic="Frontier AI Builder Interviews",
        description="Long-form interviews with AI builders, researchers, and operators working on frontier models and agentic systems.",
    ),
    Source(
        "Data Skeptic",
        "https://rss.libsyn.com/shows/54799/destinations/201630.xml",
        "research",
        "podcast",
        topic="Data Science and ML Podcast",
        description="Accessible interviews and explanations spanning machine learning, statistics, data science, and AI systems.",
    ),
    Source(
        "Me, Myself, and AI",
        "https://feeds.megaphone.fm/TPG7603691495",
        "business",
        "podcast",
        topic="Enterprise AI Podcast",
        description="MIT Sloan Management Review and BCG interview business leaders about AI strategy, adoption, and organizational change.",
    ),
    Source(
        "The AI Daily Brief",
        "https://anchor.fm/s/f7cac464/podcast/rss",
        "business",
        "podcast",
        topic="Daily AI News Analysis",
        description="Daily analysis of AI news, company moves, model launches, policy shifts, and market signals.",
    ),
    Source(
        "Machine Learning Street Talk",
        "https://anchor.fm/s/1e4a0eac/podcast/rss",
        "research",
        "podcast",
        topic="Technical ML Discussions",
        description="Deep technical conversations with AI researchers, engineers, and thinkers on models, alignment, and machine learning theory.",
    ),
    Source(
        "The Batch",
        "https://charonhub.deeplearning.ai/rss/",
        "other",
        "media",
        topic="AI News Briefing",
        description="DeepLearning.AI's weekly AI news and insight briefing on research, business, and culture.",
    ),
    Source(
        "SemiAnalysis",
        "https://www.semianalysis.com/feed",
        "infrastructure",
        "analysis",
        topic="AI Infrastructure Analysis",
        description="Deep technical and market analysis of AI chips, datacenters, model economics, and infrastructure.",
    ),
    Source(
        "MIT Technology Review AI",
        "https://www.technologyreview.com/topic/artificial-intelligence/feed/",
        "other",
        "media",
        topic="AI News Magazine",
        description="Accessible reporting and explainers on AI research, products, policy, and social impact.",
    ),
    Source(
        "The Decoder",
        "https://the-decoder.com/feed/",
        "other",
        "media",
        topic="Accessible AI News",
        description="Plain-language AI news and analysis across research, products, society, and business.",
    ),
    Source(
        "TechCrunch AI",
        "https://techcrunch.com/category/artificial-intelligence/feed/",
        "business",
        "media",
        topic="AI Startup News",
        description="Startup-oriented AI news covering product launches, companies, funding, and market shifts.",
    ),
    Source(
        "WIRED AI",
        "https://www.wired.com/feed/tag/ai/latest/rss",
        "policy",
        "media",
        topic="AI Culture and Policy",
        description="Readable journalism on AI products, policy, culture, security, and business impact.",
    ),
    Source(
        "VentureBeat AI",
        "https://venturebeat.com/category/ai/feed",
        "business",
        "media",
        topic="Enterprise AI News",
        description="Business-focused AI news and analysis on enterprise adoption, products, and market trends.",
    ),
    Source(
        "IEEE Spectrum AI",
        "https://spectrum.ieee.org/feeds/topic/artificial-intelligence.rss",
        "engineering",
        "media",
        topic="Engineering AI Magazine",
        description="Engineering-focused AI reporting from IEEE Spectrum on robotics, chips, research, and systems.",
    ),
    Source(
        "Quanta AI",
        "https://www.quantamagazine.org/tag/artificial-intelligence/feed/",
        "research",
        "media",
        topic="Science Journalism",
        description="Careful science journalism on artificial intelligence, computation, neuroscience, and machine learning research.",
    ),
    Source(
        "O'Reilly AI & ML",
        "https://www.oreilly.com/radar/topics/ai-ml/feed/",
        "engineering",
        "media",
        topic="Technology Analysis",
        description="O'Reilly Radar analysis on AI, machine learning, software architecture, and engineering practice.",
    ),
    Source(
        "Rest of World",
        "https://restofworld.org/feed/latest/",
        "applications",
        "media",
        topic="Global Technology Reporting",
        description="Global reporting on how AI and technology affect labor, markets, infrastructure, and communities.",
    ),
    Source(
        "Understanding AI",
        "https://www.understandingai.org/feed",
        "policy",
        "analysis",
        topic="AI Technology Analysis",
        description="Timothy B. Lee's reporting and analysis on AI technology, policy, and economic impact.",
    ),
    Source(
        "Marcus on AI",
        "https://garymarcus.substack.com/feed",
        "policy",
        "analysis",
        topic="AI Criticism and Policy",
        description="Gary Marcus' commentary on AI reliability, cognitive science, governance, and frontier lab claims.",
    ),
    Source(
        "AI Snake Oil",
        "https://www.aisnakeoil.com/feed",
        "safety",
        "analysis",
        topic="AI Accountability Analysis",
        description="Analysis from Sayash Kapoor and Arvind Narayanan on AI claims, risks, and deployment evidence.",
    ),
    Source(
        "AI Safety Newsletter",
        "https://newsletter.safe.ai/feed",
        "safety",
        "newsletter",
        topic="AI Safety Newsletter",
        description="Center for AI Safety updates and analysis on AI safety research, policy, and frontier AI developments.",
    ),
    Source(
        "Import AI",
        "https://jack-clark.net/feed/",
        "safety",
        "newsletter",
        topic="AI Safety and Policy Newsletter",
        description="Jack Clark's weekly analysis of AI capabilities, safety, governance, labs, and market signals.",
    ),
    Source(
        "Partnership on AI",
        "https://partnershiponai.org/feed/",
        "policy",
        "policy",
        topic="Responsible AI Nonprofit",
        description="Multistakeholder research and guidance on responsible AI, labor, media integrity, and policy.",
    ),
    Source(
        "GovAI",
        "https://www.governance.ai/post/rss.xml",
        "policy",
        "policy",
        topic="AI Governance Research",
        description="Research and commentary from the Centre for the Governance of AI on frontier AI policy and institutions.",
    ),
    Source(
        "AI Now Institute",
        "https://ainowinstitute.org/feed",
        "policy",
        "policy",
        topic="AI Accountability Institute",
        description="Research and analysis on AI accountability, public policy, labor, competition, and social impact.",
    ),
    Source(
        "Alignment Forum",
        "https://www.alignmentforum.org/feed.xml",
        "safety",
        "community",
        topic="AI Alignment Discussion",
        description="Community research discussion on technical AI alignment, safety, evaluations, and governance.",
    ),
    Source(
        "MIRI",
        "https://intelligence.org/feed/",
        "safety",
        "research",
        topic="AI Safety Research Institute",
        description="Machine Intelligence Research Institute writing on AI alignment, safety strategy, and technical risk.",
    ),
    Source(
        "EleutherAI",
        "https://blog.eleuther.ai/index.xml",
        "research",
        "community",
        topic="Open AI Research Lab",
        description="Open research updates from EleutherAI on language models, interpretability, datasets, and tooling.",
    ),
    Source(
        "GitHub AI & ML",
        "https://github.blog/ai-and-ml/feed/",
        "engineering",
        "official",
        topic="Developer AI Platform",
        description="GitHub posts on AI and machine learning for software development and open source workflows.",
    ),
    Source(
        "GitHub Changelog",
        "https://github.blog/changelog/feed/",
        "infrastructure",
        "official",
        topic="Developer Platform Releases",
        description="Product release notes and platform changes from the official GitHub Changelog.",
    ),
    Source(
        "Towards Data Science",
        "https://towardsdatascience.com/feed",
        "engineering",
        "community",
        topic="Data Science Publication",
        description="Community-authored writing on machine learning, data science, analytics, and AI engineering.",
    ),
    Source(
        "KDnuggets",
        "https://www.kdnuggets.com/feed",
        "education",
        "education",
        topic="Data Science and ML Publication",
        description="Data science and machine learning articles, tutorials, and industry commentary from KDnuggets.",
    ),
    Source(
        "Machine Learning Mastery",
        "https://machinelearningmastery.com/blog/feed/",
        "education",
        "education",
        topic="Machine Learning Education",
        description="Practical tutorials and guides on machine learning, deep learning, time series, and applied AI.",
    ),
    Source(
        "Netflix TechBlog",
        "https://medium.com/feed/netflix-techblog",
        "engineering",
        "official",
        topic="Engineering Blog",
        description="Netflix engineering posts on large-scale systems, data platforms, personalization, and ML.",
    ),
    Source(
        "Replicate Blog",
        "https://replicate.com/blog/rss",
        "engineering",
        "official",
        topic="Model Deployment Platform",
        description="Replicate updates on running, deploying, and building with open models and AI media tools.",
    ),
    Source(
        "Hacker News AI",
        "https://hnrss.org/newest?q=AI+OR+LLM&points=100",
        "other",
        "community",
        topic="Community Discussion",
        description="High-signal Hacker News discussions matching AI and LLM topics.",
    ),
    Source(
        "Simon Willison",
        "https://simonwillison.net/atom/everything/",
        "engineering",
        "independent",
        topic="AI Engineering Notebook",
        description="Simon Willison's practical notes on LLMs, software engineering, data, and developer tools.",
    ),
    Source(
        "Andrej Karpathy",
        "https://karpathy.github.io/feed.xml",
        "research",
        "independent",
        topic="AI Research and Engineering Notes",
        description="Andrej Karpathy's essays and technical notes on neural networks, language models, agents, and AI software.",
    ),
    Source(
        "Gwern",
        "https://gwern.net/rss.xml",
        "research",
        "independent",
        topic="AI Research Essays",
        description="Gwern Branwen's long-form essays and research notes on AI, scaling, alignment, and technology.",
    ),
    Source(
        "Jay Alammar",
        "https://jalammar.github.io/feed.xml",
        "education",
        "education",
        topic="Visual AI Explainers",
        description="Visual explainers and technical guides on transformers, embeddings, language models, and machine learning systems.",
    ),
    Source(
        "Chip Huyen",
        "https://huyenchip.com/feed.xml",
        "engineering",
        "independent",
        topic="ML Systems Writing",
        description="Chip Huyen's writing on machine learning systems, evaluation, deployment, and AI engineering.",
    ),
    Source(
        "Lilian Weng",
        "https://lilianweng.github.io/index.xml",
        "research",
        "research",
        topic="AI Research Notes",
        description="Lilian Weng's long-form research notes on machine learning, agents, alignment, and LLMs.",
    ),
    Source(
        "Eugene Yan",
        "https://eugeneyan.com/rss/",
        "engineering",
        "independent",
        topic="Applied ML Engineering",
        description="Eugene Yan's writing on applied machine learning systems, recommendations, and evaluation.",
    ),
    Source(
        "The Gradient",
        "https://thegradient.pub/rss/",
        "research",
        "research",
        topic="AI Research Magazine",
        description="Independent essays and interviews explaining machine learning research and AI systems.",
    ),
    Source(
        "Ahead of AI",
        "https://magazine.sebastianraschka.com/feed",
        "research",
        "newsletter",
        topic="ML Research Newsletter",
        description="Sebastian Raschka's newsletter on machine learning research, model development, and education.",
    ),
    Source(
        "arXiv cs.CL",
        "https://export.arxiv.org/rss/cs.CL",
        "research",
        "papers",
        topic="Research Preprints",
        description="Recent arXiv submissions in computation and language, including NLP and language models.",
    ),
    Source(
        "Distill",
        "https://distill.pub/rss.xml",
        "research",
        "research",
        topic="Machine Learning Research Journal",
        description="Interactive and visual explanations of machine learning research from Distill.",
    ),
    Source(
        "HF Daily Papers",
        "https://azuresilent.github.io/hf-paper-rss/feed.xml",
        "research",
        "papers",
        topic="AI Paper Feed",
        description="Daily paper feed surfaced through Hugging Face Papers for new AI research.",
    ),
    Source(
        "Dwarkesh Patel",
        "https://www.dwarkesh.com/feed",
        "research",
        "podcast",
        topic="AI Researcher Interviews",
        description="Long-form interviews with frontier AI researchers, founders, and economists on intelligence, scaling, and AI progress.",
    ),
    Source(
        "swyx",
        "https://www.swyx.io/rss.xml",
        "engineering",
        "independent",
        topic="AI Engineer Writing",
        description="Shawn Wang's personal essays on AI engineering, developer experience, and building in the AI Engineer community.",
    ),
    Source(
        "Hamel Husain",
        "https://hamel.dev/index.xml",
        "engineering",
        "independent",
        topic="Applied AI Engineering",
        description="Hamel Husain's writing on LLM evaluations, fine-tuning, applied machine learning, and AI consulting practice.",
    ),
    Source(
        "Phil Schmid",
        "https://www.philschmid.de/rss",
        "engineering",
        "independent",
        topic="Open Source AI Engineering",
        description="Philipp Schmid's technical guides on open models, fine-tuning, agents, and AI infrastructure.",
    ),
    Source(
        "Sam Altman",
        "https://blog.samaltman.com/posts.atom",
        "business",
        "independent",
        topic="OpenAI Leadership Notes",
        description="Personal essays from OpenAI CEO Sam Altman on AI, startups, and the future of technology.",
    ),
    Source(
        "fast.ai",
        "https://www.fast.ai/index.xml",
        "education",
        "education",
        topic="Practical Deep Learning",
        description="Jeremy Howard and Rachel Thomas' posts on practical deep learning, courses, libraries, and AI policy.",
    ),
    Source(
        "The Pragmatic Engineer",
        "https://newsletter.pragmaticengineer.com/feed",
        "engineering",
        "newsletter",
        topic="Software Engineering Newsletter",
        description="Gergely Orosz's newsletter on engineering practice, AI tooling, hiring, and how software teams ship at scale.",
    ),
    Source(
        "Don't Worry About the Vase",
        "https://thezvi.substack.com/feed",
        "safety",
        "analysis",
        topic="AI Weekly Roundups",
        description="Zvi Mowshowitz's long-form weekly analysis of AI capabilities, safety, policy, and frontier lab developments.",
    ),
    Source(
        "Astral Codex Ten",
        "https://www.astralcodexten.com/feed",
        "other",
        "analysis",
        topic="Rationalist Commentary",
        description="Scott Alexander's essays on AI, rationality, science, and society, frequently cited in AI discussions.",
    ),
    Source(
        "Drew Breunig",
        "https://www.dbreunig.com/feed.xml",
        "applications",
        "independent",
        topic="Applied AI Analysis",
        description="Drew Breunig's writing on applied AI, products, location data, and what's working in production AI systems.",
    ),
    Source(
        "AI ML Newsletter",
        "https://aiml.substack.com/feed",
        "engineering",
        "newsletter",
        topic="Machine Learning Newsletter",
        description="Andriy Burkov's newsletter on machine learning, AI engineering, and industry trends from the author of The Hundred-Page ML Book.",
    ),
    Source(
        "Vercel",
        "https://vercel.com/atom",
        "infrastructure",
        "official",
        topic="AI App Platform",
        description="Vercel posts on the AI SDK, AI Gateway, agents, Next.js, and shipping AI-powered applications to production.",
    ),
    Source(
        "Supabase",
        "https://supabase.com/feed.xml",
        "infrastructure",
        "official",
        topic="Open Source Backend Platform",
        description="Supabase posts on Postgres, vector storage, auth, and infrastructure that AI builders use to ship apps.",
    ),
    Source(
        "Lex Fridman Podcast",
        "https://lexfridman.com/feed/podcast/",
        "research",
        "podcast",
        topic="Long-Form Interviews",
        description="Long-form interviews with AI researchers, scientists, founders, and public intellectuals on intelligence and ideas.",
    ),
    Source(
        "Elad Gil",
        "https://blog.eladgil.com/feed",
        "business",
        "analysis",
        topic="AI Investor Commentary",
        description="Elad Gil's writing on AI markets, startups, infrastructure, and the strategic landscape from a longtime investor.",
    ),
    Source(
        "Towards AI",
        "https://pub.towardsai.net/feed",
        "education",
        "education",
        topic="Beginner-Friendly AI Publication",
        description="Community-authored tutorials, explainers, and project walk-throughs covering machine learning, LLMs, and AI fundamentals.",
    ),
    Source(
        "Analytics Vidhya",
        "https://www.analyticsvidhya.com/feed/",
        "education",
        "education",
        topic="Data Science Tutorials",
        description="Beginner-friendly tutorials and guides on data science, machine learning, deep learning, and generative AI.",
    ),
    Source(
        "NVIDIA Blog",
        "https://blogs.nvidia.com/feed/",
        "applications",
        "official",
        topic="Accessible AI Stories",
        description="Approachable NVIDIA posts explaining AI applications, industry use cases, and how generative AI is being deployed.",
    ),
    Source(
        "DAIR.AI Newsletter",
        "https://nlpnewsletter.substack.com/feed",
        "education",
        "newsletter",
        topic="NLP and Prompt Engineering",
        description="Elvis Saravia's accessible newsletter on NLP, language models, prompt engineering, and learning resources from DAIR.AI.",
    ),
    Source(
        "MarkTechPost",
        "https://www.marktechpost.com/feed/",
        "other",
        "media",
        topic="Accessible AI News",
        description="Plain-language summaries of new AI research, models, and tools written for a broad technical and beginner audience.",
    ),
    Source(
        "PyImageSearch",
        "https://www.pyimagesearch.com/feed/",
        "education",
        "education",
        topic="Computer Vision Tutorials",
        description="Adrian Rosebrock's step-by-step Python tutorials on computer vision, deep learning, and image processing for beginners.",
    ),
    Source(
        "The AI Edge",
        "https://theaiedge.substack.com/feed",
        "education",
        "newsletter",
        topic="ML System Design Tutorials",
        description="Damien Benveniste's newsletter on machine learning fundamentals, system design, and LLM concepts for engineers learning AI.",
    ),
    Source(
        "AI Tidbits",
        "https://www.aitidbits.ai/feed",
        "applications",
        "newsletter",
        topic="Accessible AI Roundup",
        description="Sahar Mor's roundup of AI news, tools, and trends written for a broad audience of builders, operators, and learners.",
    ),
    Source(
        "3Blue1Brown",
        "https://www.youtube.com/feeds/videos.xml?channel_id=UCYO_jab_esuFRV4b17AJtAw",
        "education",
        "video",
        topic="Visual Math and ML Explainers",
        description="Grant Sanderson's animated explanations of neural networks, transformers, and the mathematical foundations behind machine learning.",
    ),
    Source(
        "Two Minute Papers",
        "https://www.youtube.com/feeds/videos.xml?channel_id=UCbfYPyITQ-7l4upoX8nvctg",
        "research",
        "video",
        topic="AI Paper Summaries",
        description="Karoly Zsolnai-Feher's short, accessible video summaries of new AI, graphics, and machine learning research.",
    ),
    Source(
        "Yannic Kilcher",
        "https://www.youtube.com/feeds/videos.xml?channel_id=UCZHmQk67mSJgfCCTn7xBfew",
        "research",
        "video",
        topic="AI Paper Deep Dives",
        description="Yannic Kilcher's technical walk-throughs of recent AI and machine learning papers, with code and intuition.",
    ),
    Source(
        "Andrej Karpathy (YouTube)",
        "https://www.youtube.com/feeds/videos.xml?channel_id=UCXUPKJO5MZQN11PqgIvyuvQ",
        "education",
        "video",
        topic="LLM and Neural Network Lectures",
        description="Andrej Karpathy's long-form lectures on language models, neural networks, and how AI systems actually work end-to-end.",
    ),
    Source(
        "DeepLearningAI",
        "https://www.youtube.com/feeds/videos.xml?channel_id=UCcIXc5mJsHVYTZR1maL5l9w",
        "education",
        "video",
        topic="AI Courses and Talks",
        description="Andrew Ng's DeepLearning.AI channel with short courses, expert interviews, and accessible AI explainers.",
    ),
    Source(
        "Computerphile",
        "https://www.youtube.com/feeds/videos.xml?channel_id=UC9-y-6csu5WGm29I7JiwpnA",
        "education",
        "video",
        topic="Computer Science Explainers",
        description="Approachable computer science videos featuring AI, language models, security, and algorithms, recorded with University of Nottingham researchers.",
    ),
    Source(
        "AI Coffee Break",
        "https://www.youtube.com/feeds/videos.xml?channel_id=UCobqgqE4i5Kf7wrxRxhToQA",
        "education",
        "video",
        topic="AI Paper Explainers",
        description="Letitia Parcalabescu's accessible explainers of AI research papers, transformer models, and machine learning concepts.",
    ),
    Source(
        "sentdex",
        "https://www.youtube.com/feeds/videos.xml?channel_id=UCfzlCWGWYyIQ0aLC5w48gBQ",
        "education",
        "video",
        topic="Python AI Tutorials",
        description="Harrison Kinsley's Python tutorials on machine learning, neural networks, reinforcement learning, and practical AI projects.",
    ),
    Source(
        "Anthropic News",
        "https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_anthropic_news.xml",
        "models",
        "official",
        topic="AI Research Lab",
        description="Official Anthropic announcements on Claude products, policy, partnerships, and company news.",
    ),
    Source(
        "Anthropic Research",
        "https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_anthropic_research.xml",
        "research",
        "official",
        topic="AI Research Lab",
        description="Anthropic's research publications on interpretability, alignment, model behavior, and Claude's capabilities.",
    ),
    Source(
        "Claude Blog",
        "https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_claude.xml",
        "applications",
        "official",
        topic="Claude Product Updates",
        description="Product updates, use cases, and customer stories for Claude, Claude Code, and Claude Cowork.",
    ),
    Source(
        "Anthropic Frontier Red Team",
        "https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_anthropic_red.xml",
        "safety",
        "official",
        topic="AI Cyber and Bio Risk Research",
        description="Anthropic's Frontier Red Team research on frontier model risks, cyber capabilities, and national security evaluations.",
    ),
    Source(
        "AI at Meta",
        "https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_meta_ai.xml",
        "applications",
        "official",
        topic="AI Product Lab",
        description="Meta's official updates on Llama models, generative media tools, and AI products from the AI at Meta team.",
    ),
    Source(
        "Thinking Machines Lab",
        "https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_thinkingmachines.xml",
        "models",
        "official",
        topic="Frontier AI Lab",
        description="Research and engineering notes from Thinking Machines Lab on model training, fine-tuning, and human-AI collaboration.",
    ),
    Source(
        "Claude Code Changelog",
        "https://code.claude.com/docs/en/changelog/rss.xml",
        "engineering",
        "official",
        topic="Developer Tool Releases",
        description="Official release notes for Claude Code, covering new features, improvements, and fixes by version.",
    ),
    Source(
        "Dagster Blog",
        "https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_dagster.xml",
        "infrastructure",
        "official",
        topic="Data Orchestration Platform",
        description="Dagster engineering posts on data pipelines, orchestration, and building reliable data and AI platforms.",
    ),
    Source(
        "arXiv cs.LG",
        "https://export.arxiv.org/rss/cs.LG",
        "research",
        "papers",
        topic="Research Preprints",
        description="Recent arXiv submissions in machine learning, covering new algorithms, training methods, and theoretical results.",
    ),
)
