"""add preferred sources to user interests

Revision ID: 2a454a559d4b
Revises: e0f1a2b3c4d5
Create Date: 2026-05-07 13:31:35.452361

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a454a559d4b'
down_revision = 'e0f1a2b3c4d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_events_user_event'), table_name='article_events')
    op.add_column('user_interests', sa.Column('preferred_sources', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_interests', 'preferred_sources')
    op.create_index(op.f('ix_article_events_user_event'), 'article_events', ['user_id', 'event_type', 'article_id'], unique=False)
    # ### end Alembic commands ###
