"""Add ingest runs table

Revision ID: 86bc09927088
Revises: d1e2f3a4b5c6
Create Date: 2026-05-06 21:06:40.774410

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '86bc09927088'
down_revision = 'd1e2f3a4b5c6'
branch_labels = None
depends_on = None


INGEST_RUN_STATUS = postgresql.ENUM(
    'running',
    'succeeded',
    'failed',
    name='ingest_run_status',
    create_type=False,
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    INGEST_RUN_STATUS.create(op.get_bind(), checkfirst=True)
    op.create_table('ingest_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', INGEST_RUN_STATUS, nullable=False),
    sa.Column('inserted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('embedded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_runs_started_at'), 'ingest_runs', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingest_runs_started_at'), table_name='ingest_runs')
    op.drop_table('ingest_runs')
    INGEST_RUN_STATUS.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
