"""add article summary fields

Revision ID: d6253c279a29
Revises: 2d6f8a9c4b12
Create Date: 2026-05-04 21:13:31.385161

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd6253c279a29'
down_revision = '2d6f8a9c4b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('content_quality', sa.String(length=16), server_default='excerpt', nullable=False))
    op.add_column('articles', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('why_it_matters', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('difficulty', sa.String(length=16), nullable=True))
    op.add_column('articles', sa.Column('summary_status', sa.String(length=16), server_default='pending', nullable=False))
    op.add_column('articles', sa.Column('summary_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('articles', sa.Column('summary_prompt_version', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('summary_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('articles', 'content_quality', server_default=None)
    op.alter_column('articles', 'summary_status', server_default=None)
    op.alter_column('articles', 'summary_attempts', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'summary_generated_at')
    op.drop_column('articles', 'summary_prompt_version')
    op.drop_column('articles', 'summary_attempts')
    op.drop_column('articles', 'summary_status')
    op.drop_column('articles', 'difficulty')
    op.drop_column('articles', 'why_it_matters')
    op.drop_column('articles', 'summary')
    op.drop_column('articles', 'content_quality')
    # ### end Alembic commands ###
