/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTodayDigestRouteImport } from './routes/_layout/today-digest'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSavedArticlesRouteImport } from './routes/_layout/saved-articles'
import { Route as LayoutAllArticleSourcesRouteImport } from './routes/_layout/all-article-sources'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin.index'
import { Route as LayoutSearchFeedQRouteImport } from './routes/_layout/search-feed.$q'
import { Route as LayoutCategoryFeedCatRouteImport } from './routes/_layout/category-feed.$cat'
import { Route as LayoutArticleSourcesSRouteImport } from './routes/_layout/article-sources.$s'
import { Route as LayoutAdminIngestRunsRouteImport } from './routes/_layout/admin.ingest-runs'
import { Route as LayoutAdminArticlesRouteImport } from './routes/_layout/admin.articles'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTodayDigestRoute = LayoutTodayDigestRouteImport.update({
  id: '/today-digest',
  path: '/today-digest',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSavedArticlesRoute = LayoutSavedArticlesRouteImport.update({
  id: '/saved-articles',
  path: '/saved-articles',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAllArticleSourcesRoute = LayoutAllArticleSourcesRouteImport.update({
  id: '/all-article-sources',
  path: '/all-article-sources',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutSearchFeedQRoute = LayoutSearchFeedQRouteImport.update({
  id: '/search-feed/$q',
  path: '/search-feed/$q',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCategoryFeedCatRoute = LayoutCategoryFeedCatRouteImport.update({
  id: '/category-feed/$cat',
  path: '/category-feed/$cat',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutArticleSourcesSRoute = LayoutArticleSourcesSRouteImport.update({
  id: '/article-sources/$s',
  path: '/article-sources/$s',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminIngestRunsRoute = LayoutAdminIngestRunsRouteImport.update({
  id: '/ingest-runs',
  path: '/ingest-runs',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminArticlesRoute = LayoutAdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => LayoutAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/all-article-sources': typeof LayoutAllArticleSourcesRoute
  '/saved-articles': typeof LayoutSavedArticlesRoute
  '/settings': typeof LayoutSettingsRoute
  '/today-digest': typeof LayoutTodayDigestRoute
  '/admin/articles': typeof LayoutAdminArticlesRoute
  '/admin/ingest-runs': typeof LayoutAdminIngestRunsRoute
  '/article-sources/$s': typeof LayoutArticleSourcesSRoute
  '/category-feed/$cat': typeof LayoutCategoryFeedCatRoute
  '/search-feed/$q': typeof LayoutSearchFeedQRoute
  '/admin/': typeof LayoutAdminIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/all-article-sources': typeof LayoutAllArticleSourcesRoute
  '/saved-articles': typeof LayoutSavedArticlesRoute
  '/settings': typeof LayoutSettingsRoute
  '/today-digest': typeof LayoutTodayDigestRoute
  '/': typeof LayoutIndexRoute
  '/admin/articles': typeof LayoutAdminArticlesRoute
  '/admin/ingest-runs': typeof LayoutAdminIngestRunsRoute
  '/article-sources/$s': typeof LayoutArticleSourcesSRoute
  '/category-feed/$cat': typeof LayoutCategoryFeedCatRoute
  '/search-feed/$q': typeof LayoutSearchFeedQRoute
  '/admin': typeof LayoutAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/all-article-sources': typeof LayoutAllArticleSourcesRoute
  '/_layout/saved-articles': typeof LayoutSavedArticlesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/today-digest': typeof LayoutTodayDigestRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/articles': typeof LayoutAdminArticlesRoute
  '/_layout/admin/ingest-runs': typeof LayoutAdminIngestRunsRoute
  '/_layout/article-sources/$s': typeof LayoutArticleSourcesSRoute
  '/_layout/category-feed/$cat': typeof LayoutCategoryFeedCatRoute
  '/_layout/search-feed/$q': typeof LayoutSearchFeedQRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/all-article-sources'
    | '/saved-articles'
    | '/settings'
    | '/today-digest'
    | '/admin/articles'
    | '/admin/ingest-runs'
    | '/article-sources/$s'
    | '/category-feed/$cat'
    | '/search-feed/$q'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/all-article-sources'
    | '/saved-articles'
    | '/settings'
    | '/today-digest'
    | '/'
    | '/admin/articles'
    | '/admin/ingest-runs'
    | '/article-sources/$s'
    | '/category-feed/$cat'
    | '/search-feed/$q'
    | '/admin'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/all-article-sources'
    | '/_layout/saved-articles'
    | '/_layout/settings'
    | '/_layout/today-digest'
    | '/_layout/'
    | '/_layout/admin/articles'
    | '/_layout/admin/ingest-runs'
    | '/_layout/article-sources/$s'
    | '/_layout/category-feed/$cat'
    | '/_layout/search-feed/$q'
    | '/_layout/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/today-digest': {
      id: '/_layout/today-digest'
      path: '/today-digest'
      fullPath: '/today-digest'
      preLoaderRoute: typeof LayoutTodayDigestRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/saved-articles': {
      id: '/_layout/saved-articles'
      path: '/saved-articles'
      fullPath: '/saved-articles'
      preLoaderRoute: typeof LayoutSavedArticlesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/all-article-sources': {
      id: '/_layout/all-article-sources'
      path: '/all-article-sources'
      fullPath: '/all-article-sources'
      preLoaderRoute: typeof LayoutAllArticleSourcesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/search-feed/$q': {
      id: '/_layout/search-feed/$q'
      path: '/search-feed/$q'
      fullPath: '/search-feed/$q'
      preLoaderRoute: typeof LayoutSearchFeedQRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/category-feed/$cat': {
      id: '/_layout/category-feed/$cat'
      path: '/category-feed/$cat'
      fullPath: '/category-feed/$cat'
      preLoaderRoute: typeof LayoutCategoryFeedCatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/article-sources/$s': {
      id: '/_layout/article-sources/$s'
      path: '/article-sources/$s'
      fullPath: '/article-sources/$s'
      preLoaderRoute: typeof LayoutArticleSourcesSRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/ingest-runs': {
      id: '/_layout/admin/ingest-runs'
      path: '/ingest-runs'
      fullPath: '/admin/ingest-runs'
      preLoaderRoute: typeof LayoutAdminIngestRunsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/articles': {
      id: '/_layout/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof LayoutAdminArticlesRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminArticlesRoute: typeof LayoutAdminArticlesRoute
  LayoutAdminIngestRunsRoute: typeof LayoutAdminIngestRunsRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminArticlesRoute: LayoutAdminArticlesRoute,
  LayoutAdminIngestRunsRoute: LayoutAdminIngestRunsRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutAllArticleSourcesRoute: typeof LayoutAllArticleSourcesRoute
  LayoutSavedArticlesRoute: typeof LayoutSavedArticlesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTodayDigestRoute: typeof LayoutTodayDigestRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutArticleSourcesSRoute: typeof LayoutArticleSourcesSRoute
  LayoutCategoryFeedCatRoute: typeof LayoutCategoryFeedCatRoute
  LayoutSearchFeedQRoute: typeof LayoutSearchFeedQRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutAllArticleSourcesRoute: LayoutAllArticleSourcesRoute,
  LayoutSavedArticlesRoute: LayoutSavedArticlesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTodayDigestRoute: LayoutTodayDigestRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutArticleSourcesSRoute: LayoutArticleSourcesSRoute,
  LayoutCategoryFeedCatRoute: LayoutCategoryFeedCatRoute,
  LayoutSearchFeedQRoute: LayoutSearchFeedQRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
